site_name: 萘酚米兹哈的摆烂个人站
site_url: https://naphtholmizuha.top/

nav:
  - 主页: index.md
  - 目录: toc.md
  - 标签: tags.md
  - 关于: about.md
  - 友情链接: friends.md

theme:
  language: zh
  font: false
  name: material
  palette: 
    scheme: naph
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - toc.integrate
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra:
  consent:
    title: Cookie consent
    description: >-
      我们使用cookies识别您的访问记录以及偏好
  social:
    -
      icon: fontawesome/brands/github
      link: https://github.com/NaphtholMizuha
      name: 我的GitHub主页

plugins:
  - search
  - blogging:
      locale: zh_CN
      dirs:
        - blog
      features:
        tags:
          index_page: tags.md
          insert: top
      theme: 
        name: card
        time_format: '%Y-%m-%d %H:%M:%S'
        meta_time_format: '%Y-%m-%d %H:%M:%S'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/naph.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - javascripts/katex.js
copyright: Copyright &copy; 2022 Naphthol Mizuha
