site_name: 萘酚米兹哈的摆烂个人站
nav:
  - 主页: index.md
  - 关于: about.md
  - 友情链接: friends.md
  - 标签: tags.md
theme:
  language: zh
  font: false
  name: material
  palette: 
    scheme: naph
  features:
    - navigation.tabs
    - navigation.expand
    - content.tabs.link
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra:
  consent:
    title: Cookie consent
    description: >-
      我们使用cookies识别您的访问记录以及偏好
  social:
    -
      icon: fontawesome/brands/github
      link: https://github.com/NaphtholMizuha
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search:
      
  - glightbox
  - tags:
      tags_file: tags.md
extra_css:
  - stylesheets/naph.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2022 Naphthol Mizuha
